zcat Alzheimers_disease_Lambert_2013_NatGen_GWAS_meta_stage1.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Alzheimers_disease_Lambert_2013_NatGen_GWAS_meta_stage1.old_coords.bed
zcat CAD_C4D_cardiogram_Nikpay_2015_additive.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/CAD_C4D_cardiogram_Nikpay_2015_additive.old_coords.bed
zcat Celiac_disease_Dubois_2010_NatGen_GWAS.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Celiac_disease_Dubois_2010_NatGen_GWAS.old_coords.bed
zcat Celiac_disease_Trynka_2011_NatGen_Immunochip.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Celiac_disease_Trynka_2011_NatGen_Immunochip.old_coords.bed
zcat Creatinine.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Creatinine.unified.old_coords.bed
zcat Crohns_disease_Jostins_2012_Nature_GWAS.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Crohns_disease_Jostins_2012_Nature_GWAS.old_coords.bed
zcat CRP.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/CRP.unified.old_coords.bed
zcat Glucose.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Glucose.unified.old_coords.bed
zcat HDL.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/HDL.unified.old_coords.bed
zcat HGB.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/HGB.unified.old_coords.bed
zcat HOMA_b.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/HOMA_b.unified.old_coords.bed
zcat HOMA_ir.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/HOMA_ir.unified.old_coords.bed
zcat IL6.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/IL6.unified.old_coords.bed
zcat Inflammatory_bowel_disease_CD_Liu_2015_NatGen_Immunochip.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Inflammatory_bowel_disease_CD_Liu_2015_NatGen_Immunochip.old_coords.bed
zcat Inflammatory_bowel_disease_Liu_2015_NatGen_Immunochip.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Inflammatory_bowel_disease_Liu_2015_NatGen_Immunochip.old_coords.bed
zcat Inflammatory_bowel_disease_UC_Liu_2015_NatGen_Immunochip.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Inflammatory_bowel_disease_UC_Liu_2015_NatGen_Immunochip.old_coords.bed
zcat Insulin.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Insulin.unified.old_coords.bed
zcat LDL.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/LDL.unified.old_coords.bed
zcat MCHC.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/MCHC.unified.old_coords.bed
zcat MCH.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/MCH.unified.old_coords.bed
zcat MCV.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/MCV.unified.old_coords.bed
zcat MI_C4D_cardiogram_Nikpay_2015_additive.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/MI_C4D_cardiogram_Nikpay_2015_additive.old_coords.bed
zcat Multiple_sclerosis_IMSGC-Beecham_2013_NatGen_Immunochip.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Multiple_sclerosis_IMSGC-Beecham_2013_NatGen_Immunochip.old_coords.bed
zcat Narcolepsy_Faraco_2013_PLoSGen_Immunochip.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Narcolepsy_Faraco_2013_PLoSGen_Immunochip.old_coords.bed
zcat PCV.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/PCV.unified.old_coords.bed
zcat PLT.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/PLT.unified.old_coords.bed
zcat Primary_biliary_cirrhosis_Cordell_2015_NatCommun_GWAS_meta.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Primary_biliary_cirrhosis_Cordell_2015_NatCommun_GWAS_meta.old_coords.bed
zcat Psoriasis_Tsoi_2012_NatGen_meta_NCBI_dbGAP_GAIN.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Psoriasis_Tsoi_2012_NatGen_meta_NCBI_dbGAP_GAIN.old_coords.bed
zcat RBC.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/RBC.unified.old_coords.bed
zcat Rheumatoid_Arthritis_Eyre_2012_NatGen_Immunochip.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Rheumatoid_Arthritis_Eyre_2012_NatGen_Immunochip.old_coords.bed
zcat Rheumatoid_Arthritis_Okada_2014_Nature_GWAS_meta.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Rheumatoid_Arthritis_Okada_2014_Nature_GWAS_meta.old_coords.bed
zcat Schizophrenia_Ripke_2014_Nature_GWAS.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Schizophrenia_Ripke_2014_Nature_GWAS.old_coords.bed
zcat Systemic_lupus_erythematosus_Bentham_2015_NatGen_GWAS.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Systemic_lupus_erythematosus_Bentham_2015_NatGen_GWAS.old_coords.bed
zcat TC.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/TC.unified.old_coords.bed
zcat TG.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/TG.unified.old_coords.bed
zcat Type_1_diabetes_Onengut-Gumuscu_2015_NatGen_Immunochip_Case_control.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Type_1_diabetes_Onengut-Gumuscu_2015_NatGen_Immunochip_Case_control.old_coords.bed
zcat Type_1_diabetes_Onengut-Gumuscu_2015_NatGen_Immunochip_meta.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Type_1_diabetes_Onengut-Gumuscu_2015_NatGen_Immunochip_meta.old_coords.bed
zcat Type_2_diabetes_Morris_2012_NatGen_Metabochip_meta.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Type_2_diabetes_Morris_2012_NatGen_Metabochip_meta.old_coords.bed
zcat Type_2_diabetes_Morris_2012_NatGen_meta.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Type_2_diabetes_Morris_2012_NatGen_meta.old_coords.bed
zcat ukbb.1000g.exome.hard.meta.filter.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/ukbb.1000g.e.old_coords.bed
zcat Ulcerative_cholitis_Jostins_2012_Nature_GWAS.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Ulcerative_cholitis_Jostins_2012_Nature_GWAS.old_coords.bed
zcat Ulcerative_cholitis_Julia_2014_HumMolGenet_GWAS_meta.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/Ulcerative_cholitis_Julia_2014_HumMolGenet_GWAS_meta.old_coords.bed
zcat UricAcid.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/UricAcid.unified.old_coords.bed
zcat WBC.unified.sorted.txt.gz | python3.6 liftover_scripts/extract_coordinates_bed.py > old_coords/WBC.unified.old_coords.bed
